name: Build

on:
  pull_request:
    types: [ opened, reopened, synchronize ]
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install root dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Install dev dependencies
        run: |
          cd dev
          yarn install

      - name: Set up environment variables
        run: |
          cd dev
          echo "DATABASE_URI=mongodb://127.0.0.1:27017/test" >> .env
          echo "PAYLOAD_SECRET=hellohereisasecretforyou" >> .env

      - name: Run tests
        run: |
          yarn test
